#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPS_DIR="${DEPS_DIR:-${ROOT_DIR}/.deps}"
ESP_IDF_VERSION="${ESP_IDF_VERSION:-v5.4.1}"
ESP_MATTER_VERSION="${ESP_MATTER_VERSION:-v1.4.2}"
IDF_PATH="${IDF_PATH:-${DEPS_DIR}/esp-idf}"
ESP_MATTER_PATH="${ESP_MATTER_PATH:-${DEPS_DIR}/esp-matter}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

log() {
    printf '==> %s\n' "$*"
}

fail() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || fail "missing required command: $1"
}

install_user_cmake() {
    log "Installing user-local CMake < 4"
    if "$PYTHON_BIN" -m pip install --user --upgrade 'cmake<4' >/dev/null; then
        return
    fi
    "$PYTHON_BIN" -m pip install --user --break-system-packages --upgrade 'cmake<4' >/dev/null
}

clone_or_update_repo() {
    local repo_url="$1"
    local repo_dir="$2"
    local repo_ref="$3"
    local recursive="$4"

    if [[ ! -d "$repo_dir/.git" ]]; then
        log "Cloning $(basename "$repo_dir") at ${repo_ref}"
        if [[ "$recursive" == "1" ]]; then
            git clone --depth 1 --branch "$repo_ref" --recursive --shallow-submodules "$repo_url" "$repo_dir"
        else
            git clone --depth 1 --branch "$repo_ref" "$repo_url" "$repo_dir"
        fi
        return
    fi

    log "Updating $(basename "$repo_dir") to ${repo_ref}"
    git -C "$repo_dir" fetch --depth 1 origin "$repo_ref"
    git -C "$repo_dir" checkout --force FETCH_HEAD
    if [[ "$recursive" == "1" ]]; then
        git -C "$repo_dir" submodule update --init --recursive --depth 1
    fi
}

need_cmd git
need_cmd "$PYTHON_BIN"

PY_USER_BASE="$($PYTHON_BIN -m site --user-base)"
CMAKE_BIN_DIR="${CMAKE_BIN_DIR:-${PY_USER_BASE}/bin}"

if [[ ! -x "${CMAKE_BIN_DIR}/cmake" ]]; then
    install_user_cmake
else
    CMAKE_MAJOR="$("${CMAKE_BIN_DIR}/cmake" --version | awk 'NR==1 { split($3, version, "."); print version[1] }')"
    if [[ "${CMAKE_MAJOR}" -ge 4 ]]; then
        install_user_cmake
    fi
fi

mkdir -p "$DEPS_DIR"

clone_or_update_repo "https://github.com/espressif/esp-idf.git" "$IDF_PATH" "$ESP_IDF_VERSION" 0
clone_or_update_repo "https://github.com/espressif/esp-matter.git" "$ESP_MATTER_PATH" "$ESP_MATTER_VERSION" 1

log "Installing ESP-IDF toolchain for esp32"
bash "$IDF_PATH/install.sh" esp32

log "Bootstrapping esp-matter"
bash "$ESP_MATTER_PATH/install.sh" --no-host-tool

IDF_SERIES="${ESP_IDF_VERSION#v}"
IDF_SERIES="${IDF_SERIES%.*}"
IDF_PYTHON_ENV_PATH="${IDF_PYTHON_ENV_PATH:-$(find "$HOME/.espressif/python_env" -maxdepth 1 -type d -name "idf${IDF_SERIES}*_env" | sort | tail -n 1)}"
[[ -n "$IDF_PYTHON_ENV_PATH" ]] || fail "unable to locate ESP-IDF python environment"

ENV_FILE="$ROOT_DIR/.env.mk"
log "Writing ${ENV_FILE}"
printf '%s\n' \
    '# Autogenerated by scripts/dev-init.sh' \
    "DEPS_DIR ?= ${DEPS_DIR}" \
    "IDF_PATH ?= ${IDF_PATH}" \
    "ESP_MATTER_PATH ?= ${ESP_MATTER_PATH}" \
    "IDF_PYTHON_ENV_PATH ?= ${IDF_PYTHON_ENV_PATH}" \
    "CMAKE_BIN_DIR ?= ${CMAKE_BIN_DIR}" \
    > "$ENV_FILE"

log "Done"
printf '%s\n' \
    "  make build" \
    "  make flash PORT=/dev/tty.usbserial..."