#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPS_DIR="${DEPS_DIR:-${ROOT_DIR}/.deps}"
ESP_IDF_VERSION="${ESP_IDF_VERSION:-v5.4.1}"
ESP_MATTER_VERSION="${ESP_MATTER_VERSION:-release/v1.4.2}"
IDF_PATH="${IDF_PATH:-${DEPS_DIR}/esp-idf}"
ESP_MATTER_PATH="${ESP_MATTER_PATH:-${DEPS_DIR}/esp-matter}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

case "$(uname -s)" in
    Darwin)
        CHIP_HOST_PLATFORM="darwin"
        ;;
    Linux)
        CHIP_HOST_PLATFORM="linux"
        ;;
    *)
        fail "unsupported host OS: $(uname -s)"
        ;;
esac

log() {
    printf '==> %s\n' "$*"
}

fail() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || fail "missing required command: $1"
}

install_user_cmake() {
    log "Installing user-local CMake < 4"
    if "$PYTHON_BIN" -m pip install --user --upgrade 'cmake<4' >/dev/null; then
        return
    fi
    "$PYTHON_BIN" -m pip install --user --break-system-packages --upgrade 'cmake<4' >/dev/null
}

clone_or_update_repo() {
    local repo_url="$1"
    local repo_dir="$2"
    local repo_ref="$3"
    local recursive="$4"
    local resolved_fetch_ref=""
    local resolved_checkout_ref=""

    if git ls-remote --exit-code --heads "$repo_url" "$repo_ref" >/dev/null 2>&1; then
        resolved_fetch_ref="refs/heads/${repo_ref}"
        resolved_checkout_ref="FETCH_HEAD"
    elif git ls-remote --exit-code --tags "$repo_url" "$repo_ref" >/dev/null 2>&1; then
        resolved_fetch_ref="refs/tags/${repo_ref}"
        resolved_checkout_ref="FETCH_HEAD"
    elif git ls-remote --exit-code --tags "$repo_url" "${repo_ref}^{}" >/dev/null 2>&1; then
        resolved_fetch_ref="refs/tags/${repo_ref}^{}"
        resolved_checkout_ref="FETCH_HEAD"
    else
        fail "unable to resolve ${repo_ref} in ${repo_url}"
    fi

    if [[ ! -d "$repo_dir/.git" ]]; then
        log "Cloning $(basename "$repo_dir") at ${repo_ref}"
        git init "$repo_dir" >/dev/null
        git -C "$repo_dir" remote add origin "$repo_url"
        git -C "$repo_dir" fetch --depth 1 origin "$resolved_fetch_ref"
        git -C "$repo_dir" checkout --force "$resolved_checkout_ref"
        if [[ "$recursive" == "1" ]]; then
            git -C "$repo_dir" submodule update --init --recursive --depth 1
        fi
        return
    fi

    log "Updating $(basename "$repo_dir") to ${repo_ref}"
    git -C "$repo_dir" fetch --depth 1 origin "$resolved_fetch_ref"
    git -C "$repo_dir" checkout --force FETCH_HEAD
    if [[ "$recursive" == "1" ]]; then
        git -C "$repo_dir" submodule update --init --recursive --depth 1
    fi
}

bootstrap_esp_matter_checkout() {
    local repo_dir="$1"
    local matter_dir="${repo_dir}/connectedhomeip/connectedhomeip"

    log "Initializing esp-matter submodules"
    git -C "$repo_dir" submodule sync --recursive
    git -C "$repo_dir" submodule update --init --depth 1

    [[ -d "$matter_dir" ]] || fail "missing connectedhomeip checkout in ${matter_dir}"

    log "Checking out connectedhomeip submodules for esp32/${CHIP_HOST_PLATFORM}"
    (
        cd "$matter_dir"
        ./scripts/checkout_submodules.py --platform esp32 "$CHIP_HOST_PLATFORM" --shallow
    )
}

need_cmd git
need_cmd "$PYTHON_BIN"

PY_USER_BASE="$($PYTHON_BIN -m site --user-base)"
CMAKE_BIN_DIR="${CMAKE_BIN_DIR:-${PY_USER_BASE}/bin}"

if [[ ! -x "${CMAKE_BIN_DIR}/cmake" ]]; then
    install_user_cmake
else
    CMAKE_MAJOR="$("${CMAKE_BIN_DIR}/cmake" --version | awk 'NR==1 { split($3, version, "."); print version[1] }')"
    if [[ "${CMAKE_MAJOR}" -ge 4 ]]; then
        install_user_cmake
    fi
fi

mkdir -p "$DEPS_DIR"

clone_or_update_repo "https://github.com/espressif/esp-idf.git" "$IDF_PATH" "$ESP_IDF_VERSION" 0
clone_or_update_repo "https://github.com/espressif/esp-matter.git" "$ESP_MATTER_PATH" "$ESP_MATTER_VERSION" 0
bootstrap_esp_matter_checkout "$ESP_MATTER_PATH"

log "Installing ESP-IDF toolchain for esp32"
bash "$IDF_PATH/install.sh" esp32

log "Bootstrapping esp-matter"
bash "$ESP_MATTER_PATH/install.sh" --no-host-tool

IDF_SERIES="${ESP_IDF_VERSION#v}"
IDF_SERIES="${IDF_SERIES%.*}"
IDF_PYTHON_ENV_PATH="${IDF_PYTHON_ENV_PATH:-$(find "$HOME/.espressif/python_env" -maxdepth 1 -type d -name "idf${IDF_SERIES}*_env" | sort | tail -n 1)}"
[[ -n "$IDF_PYTHON_ENV_PATH" ]] || fail "unable to locate ESP-IDF python environment"

ENV_FILE="$ROOT_DIR/.env.mk"
log "Writing ${ENV_FILE}"
printf '%s\n' \
    '# Autogenerated by scripts/dev-init.sh' \
    "DEPS_DIR ?= ${DEPS_DIR}" \
    "IDF_PATH ?= ${IDF_PATH}" \
    "ESP_MATTER_PATH ?= ${ESP_MATTER_PATH}" \
    "IDF_PYTHON_ENV_PATH ?= ${IDF_PYTHON_ENV_PATH}" \
    "CMAKE_BIN_DIR ?= ${CMAKE_BIN_DIR}" \
    > "$ENV_FILE"

log "Done"
printf '%s\n' \
    "  make build" \
    "  make flash PORT=/dev/tty.usbserial..."